### ISSUE TITLE
Multiple instances of relying on (data-dependent) subdirectories being precreated

### ISSUE THREAD

**Issue by pontus** [hpc2n/softwareaccounting#3]
Since the aggregator sorts data to node-separated subdirectories, it would be nice if it did not rely on all those being precreated.

In short, this typically means using os.makedirs rather than os.mkdir.

**Comment by HugoStrand** [comment]
I have ran in to the same issue. Configuring the aggregator and running it gives:

```
[root@hebbe-c1 local]# sams-aggregator.py 
2020-01-14 09:15:23,346 __main__:ERROR Failed to do aggregation
2020-01-14 09:15:23,346 __main__:ERROR Failed to mkdir '/local/sams_test/archive/10000' 
Traceback (most recent call last):
  File "/usr/bin/sams-aggregator.py", line 88, in start
    l.commit()
  File "/usr/lib/python2.7/site-packages/sams/loader/File.py", line 82, in commit
    assert False, "Failed to mkdir '%s' " % out_path
AssertionError: Failed to mkdir '/local/sams_test/archive/10000' 
Traceback (most recent call last):
  File "/usr/bin/sams-aggregator.py", line 104, in <module>
    Main().start()
  File "/usr/bin/sams-aggregator.py", line 96, in start
    l.error()
  File "/usr/lib/python2.7/site-packages/sams/loader/File.py", line 62, in error
    assert False, "Failed to mkdir '%s' " % out_path
AssertionError: Failed to mkdir '/local/sams_test/error/10000' 
```

`os.makedirs` would be very convenient.

Best, Hugo
